#index:
#    path: /
#    controller: App\Controller\DefaultController::index
communications_shortcut:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'communications_get_communications'
        keepQueryParams: true
        keepRequestMethod: true

commmunications:
    resource: "../src/Resources/config/communications/routes.yaml"
    prefix: /communications
    name_prefix: communications_
    trailing_slash_on_root: false